# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_borrow', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user_portal.User'),
        ),
    ]
