# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab01_authserver_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
