# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab01_authserver_app', '0002_auto_20170131_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtoken', models.CharField(max_length=200)),
                ('issued', models.DateTimeField(verbose_name='date issued')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab01_authserver_app.User')),
            ],
        ),
    ]
