# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab01_authserver_app', '0003_refreshtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='id',
        ),
        migrations.RemoveField(
            model_name='authgrantcode',
            name='id',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='id',
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='client_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='client_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authgrantcode',
            name='code',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='rtoken',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
