# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Print',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('page_count', models.IntegerField()),
                ('authors', models.CharField(blank=True, max_length=200)),
                ('year', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
